package responses

type ToOperationComponent struct {
	D struct {
		Results []struct {
			Metadata struct {
				ID   string `json:"id"`
				URI  string `json:"uri"`
				Type string `json:"type"`
			} `json:"__metadata"`
			MaintenanceOrder               string      `json:"MaintenanceOrder"`
			MaintenanceOrderOperation      string      `json:"MaintenanceOrderOperation"`
			MaintenanceOrderSubOperation   string      `json:"MaintenanceOrderSubOperation"`
			MaintenanceOrderComponent      string      `json:"MaintenanceOrderComponent"`
			Reservation                    string      `json:"Reservation"`
			ReservationItem                string      `json:"ReservationItem"`
			ReservationType                string      `json:"ReservationType"`
			MaintOrderRoutingNumber        string      `json:"MaintOrderRoutingNumber"`
			MaintOrderOperationCounter     string      `json:"MaintOrderOperationCounter"`
			Product                        string      `json:"Product"`
			MaintOrdOperationComponentText string      `json:"MaintOrdOperationComponentText"`
			MaintOrdOpCompRequiredQuantity string      `json:"MaintOrdOpCompRequiredQuantity"`
			BaseUnit                       string      `json:"BaseUnit"`
			QuantityInUnitOfEntry          string      `json:"QuantityInUnitOfEntry"`
			UnitOfEntry                    string      `json:"UnitOfEntry"`
			RequirementDate                string      `json:"RequirementDate"`
			RequirementTime                string      `json:"RequirementTime"`
			Supplier                       string      `json:"Supplier"`
			Plant                          string      `json:"Plant"`
			StorageLocation                string      `json:"StorageLocation"`
			MaintOrdOpCompItemCategory     string      `json:"MaintOrdOpCompItemCategory"`
			GoodsMovementType              string      `json:"GoodsMovementType"`
			ReservationIsFinallyIssued     bool        `json:"ReservationIsFinallyIssued"`
			MaterialGroup                  string      `json:"MaterialGroup"`
			ProductTypeCode                string      `json:"ProductTypeCode"`
			ServicePerformer               string      `json:"ServicePerformer"`
			PerformancePeriodStartDateTime string      `json:"PerformancePeriodStartDateTime"`
			PerformancePeriodStartDate     string      `json:"PerformancePeriodStartDate"`
			PerformancePeriodEndDate       string      `json:"PerformancePeriodEndDate"`
			PerformancePeriodEndDateTime   string      `json:"PerformancePeriodEndDateTime"`
			PerformancePeriodStartTime     string      `json:"PerformancePeriodStartTime"`
			PerformancePeriodEndTime       string      `json:"PerformancePeriodEndTime"`
			LeanServiceDuration            string      `json:"LeanServiceDuration"`
			LeanServiceDurationUnit        string      `json:"LeanServiceDurationUnit"`
			DistributionFunction           string      `json:"DistributionFunction"`
			SrvcSchedgIsAlignedWthOpWrkCtr bool        `json:"SrvcSchedgIsAlignedWthOpWrkCtr"`
			MaintOrderCompDebitCreditCode  string      `json:"MaintOrderCompDebitCreditCode"`
			GoodsMovementIsAllowed         bool        `json:"GoodsMovementIsAllowed"`
			MaintenanceOrderComponentBatch string      `json:"MaintenanceOrderComponentBatch"`
			QuantityIsFixed                bool        `json:"QuantityIsFixed"`
			MaintOrdOpComponentGLAccount   string      `json:"MaintOrdOpComponentGLAccount"`
			MaintOrdOpCompCostingRelevancy string      `json:"MaintOrdOpCompCostingRelevancy"`
			MaintCompAltvProdUsgeRateInPct string      `json:"MaintCompAltvProdUsgeRateInPct"`
			MaintOrderOpComponentSortText  string      `json:"MaintOrderOpComponentSortText"`
			MaintOrdOpCompIsBulkProduct    bool        `json:"MaintOrdOpCompIsBulkProduct"`
			MaterialProvisionType          string      `json:"MaterialProvisionType"`
			MaintOrdOpCompAssgdWBSElmntInt string      `json:"MaintOrdOpCompAssgdWBSElmntInt"`
			MaintOrderOpComponentPrice     string      `json:"MaintOrderOpComponentPrice"`
			MaintOrdOpComponentCurrency    string      `json:"MaintOrdOpComponentCurrency"`
			MatlCompIsMarkedForBackflush   bool        `json:"MatlCompIsMarkedForBackflush"`
			PurchasingGroup                string      `json:"PurchasingGroup"`
			DeliveryTimeInDays             string      `json:"DeliveryTimeInDays"`
			MaintOrdOpCompGdsRecipientName string      `json:"MaintOrdOpCompGdsRecipientName"`
			MaintOrdOpCompUnloadingPtTxt   string      `json:"MaintOrdOpCompUnloadingPtTxt"`
			GoodsReceiptDurationInWorkDays string      `json:"GoodsReceiptDurationInWorkDays"`
			PurchasingInfoRecord           string      `json:"PurchasingInfoRecord"`
			OperationLeadTimeOffset        string      `json:"OperationLeadTimeOffset"`
			OpsLeadTimeOffsetUnit          string      `json:"OpsLeadTimeOffsetUnit"`
			MaintOrdOpCompRequisitioner    string      `json:"MaintOrdOpCompRequisitioner"`
			MaintOrdOpCompProcmtTrckgNmbr  string      `json:"MaintOrdOpCompProcmtTrckgNmbr"`
			ResponsiblePurchaseOrg         string      `json:"ResponsiblePurchaseOrg"`
			MaintOrdOpCompSpecialStockType string      `json:"MaintOrdOpCompSpecialStockType"`
			VariableSizeDimension1         string      `json:"VariableSizeDimension1"`
			VariableSizeDimensionUnit      string      `json:"VariableSizeDimensionUnit"`
			VariableSizeCompFormulaKey     string      `json:"VariableSizeCompFormulaKey"`
			VariableSizeDimension2         string      `json:"VariableSizeDimension2"`
			NumberOfVariableSizeItem       int         `json:"NumberOfVariableSizeItem"`
			VariableSizeDimension3         string      `json:"VariableSizeDimension3"`
			VariableSizeItemQuantity       string      `json:"VariableSizeItemQuantity"`
			VariableSizeComponentUnit      string      `json:"VariableSizeComponentUnit"`
			RqmtDateIsEnteredManually      bool        `json:"RqmtDateIsEnteredManually"`
			SupplierProduct                string      `json:"SupplierProduct"`
			MaintOrdCompPurOutlineAgrmtItm string      `json:"MaintOrdCompPurOutlineAgrmtItm"`
			MaintOrderComponentInternalID  string      `json:"MaintOrderComponentInternalID"`
			PurchaseRequisition            string      `json:"PurchaseRequisition"`
			PurchaseRequisitionItem        string      `json:"PurchaseRequisitionItem"`
			OverallLimitAmount             string      `json:"OverallLimitAmount"`
			ExpectedOverallLimitAmount     string      `json:"ExpectedOverallLimitAmount"`
		} `json:"results"`
	} `json:"d"`
}
