package responses

type ToOperation struct {
	D struct {
		Results []struct {
			Metadata struct {
				ID   string `json:"id"`
				URI  string `json:"uri"`
				Type string `json:"type"`
			} `json:"__metadata"`
			MaintenanceOrder               string      `json:"MaintenanceOrder"`
			MaintenanceOrderOperation      string      `json:"MaintenanceOrderOperation"`
			MaintenanceOrderSubOperation   string      `json:"MaintenanceOrderSubOperation"`
			OperationControlKey            string      `json:"OperationControlKey"`
			OperationWorkCenterInternalID  string      `json:"OperationWorkCenterInternalID"`
			WorkCenter                     string      `json:"WorkCenter"`
			Plant                          string      `json:"Plant"`
			OperationStandardTextCode      string      `json:"OperationStandardTextCode"`
			OperationDescription           string      `json:"OperationDescription"`
			MaintOrderRoutingNumber        string      `json:"MaintOrderRoutingNumber"`
			MaintenanceOrderRoutingNode    string      `json:"MaintenanceOrderRoutingNode"`
			SuperiorOperationInternalID    string      `json:"SuperiorOperationInternalID"`
			OperationWorkCenterTypeCode    string      `json:"OperationWorkCenterTypeCode"`
			Language                       string      `json:"Language"`
			NumberOfTimeTickets            string      `json:"NumberOfTimeTickets"`
			OperationPurgInfoRecdSearchTxt string      `json:"OperationPurgInfoRecdSearchTxt"`
			OperationSupplier              string      `json:"OperationSupplier"`
			CostElement                    string      `json:"CostElement"`
			OperationPurchasingInfoRecord  string      `json:"OperationPurchasingInfoRecord"`
			PurchasingOrganization         string      `json:"PurchasingOrganization"`
			PurchasingGroup                string      `json:"PurchasingGroup"`
			MaterialGroup                  string      `json:"MaterialGroup"`
			OpPurchaseOutlineAgreement     string      `json:"OpPurchaseOutlineAgreement"`
			OpPurchaseOutlineAgreementItem string      `json:"OpPurchaseOutlineAgreementItem"`
			OperationRequisitionerName     string      `json:"OperationRequisitionerName"`
			OperationTrackingNumber        string      `json:"OperationTrackingNumber"`
			NumberOfCapacities             int         `json:"NumberOfCapacities"`
			OperationWorkPercent           int         `json:"OperationWorkPercent"`
			OperationCalculationControl    string      `json:"OperationCalculationControl"`
			ActivityType                   string      `json:"ActivityType"`
			OperationSystemCondition       string      `json:"OperationSystemCondition"`
			OperationGoodsRecipientName    string      `json:"OperationGoodsRecipientName"`
			OperationUnloadingPointName    string      `json:"OperationUnloadingPointName"`
			OperationPersonResponsible     string      `json:"OperationPersonResponsible"`
			DeliveryTimeInDays             string      `json:"DeliveryTimeInDays"`
			MaintOrderOperationDuration    string      `json:"MaintOrderOperationDuration"`
			MaintOrdOperationDurationUnit  string      `json:"MaintOrdOperationDurationUnit"`
			OpBscStartDateConstraintType   string      `json:"OpBscStartDateConstraintType"`
			OpBscEndDateConstraintType     string      `json:"OpBscEndDateConstraintType"`
			MaintOrdOperationWorkDuration  string      `json:"MaintOrdOperationWorkDuration"`
			MaintOrdOpWorkDurationUnit     string      `json:"MaintOrdOpWorkDurationUnit"`
			MaintOrdOpConstraintStrtDteTme string      `json:"MaintOrdOpConstraintStrtDteTme"`
			ConstraintDateForBscStartDate  string      `json:"ConstraintDateForBscStartDate"`
			ConstraintTimeForBscStartTime  string      `json:"ConstraintTimeForBscStartTime"`
			MaintOrdOpCstrtFinishDteTme    string      `json:"MaintOrdOpCstrtFinishDteTme"`
			ConstraintDateForBscFinishDate string      `json:"ConstraintDateForBscFinishDate"`
			ConstraintTimeForBscFinishTime string      `json:"ConstraintTimeForBscFinishTime"`
			MaintOrdOperationExecutionRate string      `json:"MaintOrdOperationExecutionRate"`
			Equipment                      string      `json:"Equipment"`
			FunctionalLocation             string      `json:"FunctionalLocation"`
			MaintenanceActivityType        string      `json:"MaintenanceActivityType"`
			BusinessArea                   string      `json:"BusinessArea"`
			ProfitCenter                   string      `json:"ProfitCenter"`
			FunctionalArea                 string      `json:"FunctionalArea"`
			MaintControllingObjectClass    string      `json:"MaintControllingObjectClass"`
			WrkCtrIntCapRqmtsDistr         string      `json:"WrkCtrIntCapRqmtsDistr"`
			MaintOrdOperationOverheadCode  string      `json:"MaintOrdOperationOverheadCode"`
			MaintOrderOperationQuantity    string      `json:"MaintOrderOperationQuantity"`
			MaintOrdOperationQuantityUnit  string      `json:"MaintOrdOperationQuantityUnit"`
			Assembly                       string      `json:"Assembly"`
			MaintOperationExecStageCode    string      `json:"MaintOperationExecStageCode"`
			WBSElement                     string      `json:"WBSElement"`
			IsMarkedForDeletion            bool        `json:"IsMarkedForDeletion"`
			MaintOrderOperationInternalID  string      `json:"MaintOrderOperationInternalID"`
			MaintenanceObjectListItem      int         `json:"MaintenanceObjectListItem"`
			PurchaseRequisition            string      `json:"PurchaseRequisition"`
			PurchaseRequisitionItem        string      `json:"PurchaseRequisitionItem"`
			OpErlstSchedldExecStrtDte      string      `json:"OpErlstSchedldExecStrtDte"`
			OpErlstSchedldExecStrtTme      string      `json:"OpErlstSchedldExecStrtTme"`
			OpErlstSchedldExecEndDte       string      `json:"OpErlstSchedldExecEndDte"`
			OpErlstSchedldExecEndTme       string      `json:"OpErlstSchedldExecEndTme"`
			OpLtstSchedldExecStrtDte       string      `json:"OpLtstSchedldExecStrtDte"`
			OpLtstSchedldExecStrtTme       string      `json:"OpLtstSchedldExecStrtTme"`
			OpLtstSchedldExecEndDte        string      `json:"OpLtstSchedldExecEndDte"`
			OpLtstSchedldExecEndTme        string      `json:"OpLtstSchedldExecEndTme"`
			OpActualExecutionStartDate     string      `json:"OpActualExecutionStartDate"`
			OpActualExecutionStartTime     string      `json:"OpActualExecutionStartTime"`
			OpActualExecutionEndDate       string      `json:"OpActualExecutionEndDate"`
			OpActualExecutionEndTime       string      `json:"OpActualExecutionEndTime"`
			ForecastWorkQuantity           string      `json:"ForecastWorkQuantity"`
			ActualWorkQuantity             string      `json:"ActualWorkQuantity"`
			MaintOrdOpProcessPhaseCode     string      `json:"MaintOrdOpProcessPhaseCode"`
			MaintOrdOpProcessSubPhaseCode  string      `json:"MaintOrdOpProcessSubPhaseCode"`
			SystemStatusText               string      `json:"SystemStatusText"`
			UserStatusText                 string      `json:"UserStatusText"`
			ToOperationComponent struct {
				Deferred struct {
					URI string `json:"uri"`
				} `json:"__deferred"`
			} `json:"to_MaintOrderOpComponent"`
		} `json:"results"`
	} `json:"d"`
}
