package sap_api_output_formatter

type MaintenanceOrder struct {
	ConnectionKey     string `json:"connection_key"`
	Result            bool   `json:"result"`
	RedisKey          string `json:"redis_key"`
	Filepath          string `json:"filepath"`
	APISchema         string `json:"api_schema"`
	MaintenanceOrder  string `json:"maintenance_order"`
	Deleted           bool   `json:"deleted"`
}    
    
type Header struct {
	MaintenanceOrder               string      `json:"MaintenanceOrder"`
	MaintOrderRoutingNumber        string      `json:"MaintOrderRoutingNumber"`
	MaintenanceOrderType           string      `json:"MaintenanceOrderType"`
	MaintenanceOrderDesc           string      `json:"MaintenanceOrderDesc"`
	MaintOrdBasicStartDateTime     string      `json:"MaintOrdBasicStartDateTime"`
	MaintOrdBasicEndDateTime       string      `json:"MaintOrdBasicEndDateTime"`
	MaintOrdBasicStartDate         string      `json:"MaintOrdBasicStartDate"`
	MaintOrdBasicStartTime         string      `json:"MaintOrdBasicStartTime"`
	MaintOrdBasicEndDate           string      `json:"MaintOrdBasicEndDate"`
	MaintOrdBasicEndTime           string      `json:"MaintOrdBasicEndTime"`
	MaintOrdSchedldBscStrtDateTime string      `json:"MaintOrdSchedldBscStrtDateTime"`
	MaintOrdSchedldBscEndDateTime  string      `json:"MaintOrdSchedldBscEndDateTime"`
	ScheduledBasicStartDate        string      `json:"ScheduledBasicStartDate"`
	ScheduledBasicStartTime        string      `json:"ScheduledBasicStartTime"`
	ScheduledBasicEndDate          string      `json:"ScheduledBasicEndDate"`
	ScheduledBasicEndTime          string      `json:"ScheduledBasicEndTime"`
	MaintenanceNotification        string      `json:"MaintenanceNotification"`
	OrdIsNotSchedldAutomatically   string      `json:"OrdIsNotSchedldAutomatically"`
	MainWorkCenterInternalID       string      `json:"MainWorkCenterInternalID"`
	MainWorkCenterTypeCode         string      `json:"MainWorkCenterTypeCode"`
	MainWorkCenter                 string      `json:"MainWorkCenter"`
	MainWorkCenterPlant            string      `json:"MainWorkCenterPlant"`
	WorkCenterInternalID           string      `json:"WorkCenterInternalID"`
	WorkCenterTypeCode             string      `json:"WorkCenterTypeCode"`
	WorkCenter                     string      `json:"WorkCenter"`
	MaintenancePlanningPlant       string      `json:"MaintenancePlanningPlant"`
	MaintenancePlant               string      `json:"MaintenancePlant"`
	Assembly                       string      `json:"Assembly"`
	MaintOrdProcessPhaseCode       string      `json:"MaintOrdProcessPhaseCode"`
	MaintOrdProcessSubPhaseCode    string      `json:"MaintOrdProcessSubPhaseCode"`
	BusinessArea                   string      `json:"BusinessArea"`
	CompanyCode                    string      `json:"CompanyCode"`
	CostCenter                     string      `json:"CostCenter"`
	ReferenceElement               string      `json:"ReferenceElement"`
	FunctionalArea                 string      `json:"FunctionalArea"`
	AdditionalDeviceData           string      `json:"AdditionalDeviceData"`
	Equipment                      string      `json:"Equipment"`
	EquipmentName                  string      `json:"EquipmentName"`
	FunctionalLocation             string      `json:"FunctionalLocation"`
	MaintenanceOrderPlanningCode   string      `json:"MaintenanceOrderPlanningCode"`
	MaintenancePlannerGroup        string      `json:"MaintenancePlannerGroup"`
	MaintenanceActivityType        string      `json:"MaintenanceActivityType"`
	MaintPriority                  string      `json:"MaintPriority"`
	MaintPriorityType              string      `json:"MaintPriorityType"`
	OrderProcessingGroup           string      `json:"OrderProcessingGroup"`
	ProfitCenter                   string      `json:"ProfitCenter"`
	ResponsibleCostCenter          string      `json:"ResponsibleCostCenter"`
	MaintenanceRevision            string      `json:"MaintenanceRevision"`
	SerialNumber                   string      `json:"SerialNumber"`
	SuperiorProjectNetwork         string      `json:"SuperiorProjectNetwork"`
	OperationSystemCondition       string      `json:"OperationSystemCondition"`
	WBSElement                     string      `json:"WBSElement"`
	WBSElementInternalID           string      `json:"WBSElementInternalID"`
	ControllingObjectClass         string      `json:"ControllingObjectClass"`
	MaintenanceOrderInternalID     string      `json:"MaintenanceOrderInternalID"`
	MaintenanceObjectList          string      `json:"MaintenanceObjectList"`
	MaintObjectLocAcctAssgmtNmbr   string      `json:"MaintObjectLocAcctAssgmtNmbr"`
	AssetLocation                  string      `json:"AssetLocation"`
	AssetRoom                      string      `json:"AssetRoom"`
	PlantSection                   string      `json:"PlantSection"`
	BasicSchedulingType            string      `json:"BasicSchedulingType"`
	LatestAcceptableCompletionDate string      `json:"LatestAcceptableCompletionDate"`
	MaintOrdPersonResponsible      string      `json:"MaintOrdPersonResponsible"`
	LastChangeDateTime             string      `json:"LastChangeDateTime"`
	ControllingSettlementProfile   string      `json:"ControllingSettlementProfile"`
	SystemStatusText               string      `json:"SystemStatusText"`
	UserStatusText                 string      `json:"UserStatusText"`
	TechnicalObject                string      `json:"TechnicalObject"`
	TechnicalObjectLabel           string      `json:"TechnicalObjectLabel"`
	TechObjIsEquipOrFuncnlLoc      string      `json:"TechObjIsEquipOrFuncnlLoc"`
	ToOperation                    string      `json:"to_MaintenanceOrderOperation"`
	ToObjectListItem               string      `json:"to_MaintOrderObjectListItem"`
}

type ToObjectListItem struct {
	MaintenanceOrder            string `json:"MaintenanceOrder"`
	MaintenanceOrderObjectList  string `json:"MaintenanceOrderObjectList"`
	MaintenanceObjectListItem   int    `json:"MaintenanceObjectListItem"`
	Equipment                   string `json:"Equipment"`
	MaintenanceNotification     string `json:"MaintenanceNotification"`
	Assembly                    string `json:"Assembly"`
	Material                    string `json:"Material"`
	SerialNumber                string `json:"SerialNumber"`
	UniqueItemIdentifier        string `json:"UniqueItemIdentifier"`
	FunctionalLocation          string `json:"FunctionalLocation"`
	MaintObjectListItemSequence string `json:"MaintObjectListItemSequence"`
}

type ToOperation struct {
	MaintenanceOrder               string      `json:"MaintenanceOrder"`
	MaintenanceOrderOperation      string      `json:"MaintenanceOrderOperation"`
	MaintenanceOrderSubOperation   string      `json:"MaintenanceOrderSubOperation"`
	OperationControlKey            string      `json:"OperationControlKey"`
	OperationWorkCenterInternalID  string      `json:"OperationWorkCenterInternalID"`
	WorkCenter                     string      `json:"WorkCenter"`
	Plant                          string      `json:"Plant"`
	OperationStandardTextCode      string      `json:"OperationStandardTextCode"`
	OperationDescription           string      `json:"OperationDescription"`
	MaintOrderRoutingNumber        string      `json:"MaintOrderRoutingNumber"`
	MaintenanceOrderRoutingNode    string      `json:"MaintenanceOrderRoutingNode"`
	SuperiorOperationInternalID    string      `json:"SuperiorOperationInternalID"`
	OperationWorkCenterTypeCode    string      `json:"OperationWorkCenterTypeCode"`
	Language                       string      `json:"Language"`
	NumberOfTimeTickets            string      `json:"NumberOfTimeTickets"`
	OperationPurgInfoRecdSearchTxt string      `json:"OperationPurgInfoRecdSearchTxt"`
	OperationSupplier              string      `json:"OperationSupplier"`
	CostElement                    string      `json:"CostElement"`
	OperationPurchasingInfoRecord  string      `json:"OperationPurchasingInfoRecord"`
	PurchasingOrganization         string      `json:"PurchasingOrganization"`
	PurchasingGroup                string      `json:"PurchasingGroup"`
	MaterialGroup                  string      `json:"MaterialGroup"`
	OpPurchaseOutlineAgreement     string      `json:"OpPurchaseOutlineAgreement"`
	OpPurchaseOutlineAgreementItem string      `json:"OpPurchaseOutlineAgreementItem"`
	OperationRequisitionerName     string      `json:"OperationRequisitionerName"`
	OperationTrackingNumber        string      `json:"OperationTrackingNumber"`
	NumberOfCapacities             int         `json:"NumberOfCapacities"`
	OperationWorkPercent           int         `json:"OperationWorkPercent"`
	OperationCalculationControl    string      `json:"OperationCalculationControl"`
	ActivityType                   string      `json:"ActivityType"`
	OperationSystemCondition       string      `json:"OperationSystemCondition"`
	OperationGoodsRecipientName    string      `json:"OperationGoodsRecipientName"`
	OperationUnloadingPointName    string      `json:"OperationUnloadingPointName"`
	OperationPersonResponsible     string      `json:"OperationPersonResponsible"`
	DeliveryTimeInDays             string      `json:"DeliveryTimeInDays"`
	MaintOrderOperationDuration    string      `json:"MaintOrderOperationDuration"`
	MaintOrdOperationDurationUnit  string      `json:"MaintOrdOperationDurationUnit"`
	OpBscStartDateConstraintType   string      `json:"OpBscStartDateConstraintType"`
	OpBscEndDateConstraintType     string      `json:"OpBscEndDateConstraintType"`
	MaintOrdOperationWorkDuration  string      `json:"MaintOrdOperationWorkDuration"`
	MaintOrdOpWorkDurationUnit     string      `json:"MaintOrdOpWorkDurationUnit"`
	MaintOrdOpConstraintStrtDteTme string      `json:"MaintOrdOpConstraintStrtDteTme"`
	ConstraintDateForBscStartDate  string      `json:"ConstraintDateForBscStartDate"`
	ConstraintTimeForBscStartTime  string      `json:"ConstraintTimeForBscStartTime"`
	MaintOrdOpCstrtFinishDteTme    string      `json:"MaintOrdOpCstrtFinishDteTme"`
	ConstraintDateForBscFinishDate string      `json:"ConstraintDateForBscFinishDate"`
	ConstraintTimeForBscFinishTime string      `json:"ConstraintTimeForBscFinishTime"`
	MaintOrdOperationExecutionRate string      `json:"MaintOrdOperationExecutionRate"`
	Equipment                      string      `json:"Equipment"`
	FunctionalLocation             string      `json:"FunctionalLocation"`
	MaintenanceActivityType        string      `json:"MaintenanceActivityType"`
	BusinessArea                   string      `json:"BusinessArea"`
	ProfitCenter                   string      `json:"ProfitCenter"`
	FunctionalArea                 string      `json:"FunctionalArea"`
	MaintControllingObjectClass    string      `json:"MaintControllingObjectClass"`
	WrkCtrIntCapRqmtsDistr         string      `json:"WrkCtrIntCapRqmtsDistr"`
	MaintOrdOperationOverheadCode  string      `json:"MaintOrdOperationOverheadCode"`
	MaintOrderOperationQuantity    string      `json:"MaintOrderOperationQuantity"`
	MaintOrdOperationQuantityUnit  string      `json:"MaintOrdOperationQuantityUnit"`
	Assembly                       string      `json:"Assembly"`
	MaintOperationExecStageCode    string      `json:"MaintOperationExecStageCode"`
	WBSElement                     string      `json:"WBSElement"`
	IsMarkedForDeletion            bool        `json:"IsMarkedForDeletion"`
	MaintOrderOperationInternalID  string      `json:"MaintOrderOperationInternalID"`
	MaintenanceObjectListItem      int         `json:"MaintenanceObjectListItem"`
	PurchaseRequisition            string      `json:"PurchaseRequisition"`
	PurchaseRequisitionItem        string      `json:"PurchaseRequisitionItem"`
	OpErlstSchedldExecStrtDte      string      `json:"OpErlstSchedldExecStrtDte"`
	OpErlstSchedldExecStrtTme      string      `json:"OpErlstSchedldExecStrtTme"`
	OpErlstSchedldExecEndDte       string      `json:"OpErlstSchedldExecEndDte"`
	OpErlstSchedldExecEndTme       string      `json:"OpErlstSchedldExecEndTme"`
	OpLtstSchedldExecStrtDte       string      `json:"OpLtstSchedldExecStrtDte"`
	OpLtstSchedldExecStrtTme       string      `json:"OpLtstSchedldExecStrtTme"`
	OpLtstSchedldExecEndDte        string      `json:"OpLtstSchedldExecEndDte"`
	OpLtstSchedldExecEndTme        string      `json:"OpLtstSchedldExecEndTme"`
	OpActualExecutionStartDate     string      `json:"OpActualExecutionStartDate"`
	OpActualExecutionStartTime     string      `json:"OpActualExecutionStartTime"`
	OpActualExecutionEndDate       string      `json:"OpActualExecutionEndDate"`
	OpActualExecutionEndTime       string      `json:"OpActualExecutionEndTime"`
	ForecastWorkQuantity           string      `json:"ForecastWorkQuantity"`
	ActualWorkQuantity             string      `json:"ActualWorkQuantity"`
	MaintOrdOpProcessPhaseCode     string      `json:"MaintOrdOpProcessPhaseCode"`
	MaintOrdOpProcessSubPhaseCode  string      `json:"MaintOrdOpProcessSubPhaseCode"`
	SystemStatusText               string      `json:"SystemStatusText"`
	UserStatusText                 string      `json:"UserStatusText"`
	ToOperationComponent           string      `json:"to_MaintOrderOpComponent"`
}

type ToOperationComponent struct {
	MaintenanceOrder               string      `json:"MaintenanceOrder"`
	MaintenanceOrderOperation      string      `json:"MaintenanceOrderOperation"`
	MaintenanceOrderSubOperation   string      `json:"MaintenanceOrderSubOperation"`
	MaintenanceOrderComponent      string      `json:"MaintenanceOrderComponent"`
	Reservation                    string      `json:"Reservation"`
	ReservationItem                string      `json:"ReservationItem"`
	ReservationType                string      `json:"ReservationType"`
	MaintOrderRoutingNumber        string      `json:"MaintOrderRoutingNumber"`
	MaintOrderOperationCounter     string      `json:"MaintOrderOperationCounter"`
	Product                        string      `json:"Product"`
	MaintOrdOperationComponentText string      `json:"MaintOrdOperationComponentText"`
	MaintOrdOpCompRequiredQuantity string      `json:"MaintOrdOpCompRequiredQuantity"`
	BaseUnit                       string      `json:"BaseUnit"`
	QuantityInUnitOfEntry          string      `json:"QuantityInUnitOfEntry"`
	UnitOfEntry                    string      `json:"UnitOfEntry"`
	RequirementDate                string      `json:"RequirementDate"`
	RequirementTime                string      `json:"RequirementTime"`
	Supplier                       string      `json:"Supplier"`
	Plant                          string      `json:"Plant"`
	StorageLocation                string      `json:"StorageLocation"`
	MaintOrdOpCompItemCategory     string      `json:"MaintOrdOpCompItemCategory"`
	GoodsMovementType              string      `json:"GoodsMovementType"`
	ReservationIsFinallyIssued     bool        `json:"ReservationIsFinallyIssued"`
	MaterialGroup                  string      `json:"MaterialGroup"`
	ProductTypeCode                string      `json:"ProductTypeCode"`
	ServicePerformer               string      `json:"ServicePerformer"`
	PerformancePeriodStartDateTime string      `json:"PerformancePeriodStartDateTime"`
	PerformancePeriodStartDate     string      `json:"PerformancePeriodStartDate"`
	PerformancePeriodEndDate       string      `json:"PerformancePeriodEndDate"`
	PerformancePeriodEndDateTime   string      `json:"PerformancePeriodEndDateTime"`
	PerformancePeriodStartTime     string      `json:"PerformancePeriodStartTime"`
	PerformancePeriodEndTime       string      `json:"PerformancePeriodEndTime"`
	LeanServiceDuration            string      `json:"LeanServiceDuration"`
	LeanServiceDurationUnit        string      `json:"LeanServiceDurationUnit"`
	DistributionFunction           string      `json:"DistributionFunction"`
	SrvcSchedgIsAlignedWthOpWrkCtr bool        `json:"SrvcSchedgIsAlignedWthOpWrkCtr"`
	MaintOrderCompDebitCreditCode  string      `json:"MaintOrderCompDebitCreditCode"`
	GoodsMovementIsAllowed         bool        `json:"GoodsMovementIsAllowed"`
	MaintenanceOrderComponentBatch string      `json:"MaintenanceOrderComponentBatch"`
	QuantityIsFixed                bool        `json:"QuantityIsFixed"`
	MaintOrdOpComponentGLAccount   string      `json:"MaintOrdOpComponentGLAccount"`
	MaintOrdOpCompCostingRelevancy string      `json:"MaintOrdOpCompCostingRelevancy"`
	MaintCompAltvProdUsgeRateInPct string      `json:"MaintCompAltvProdUsgeRateInPct"`
	MaintOrderOpComponentSortText  string      `json:"MaintOrderOpComponentSortText"`
	MaintOrdOpCompIsBulkProduct    bool        `json:"MaintOrdOpCompIsBulkProduct"`
	MaterialProvisionType          string      `json:"MaterialProvisionType"`
	MaintOrdOpCompAssgdWBSElmntInt string      `json:"MaintOrdOpCompAssgdWBSElmntInt"`
	MaintOrderOpComponentPrice     string      `json:"MaintOrderOpComponentPrice"`
	MaintOrdOpComponentCurrency    string      `json:"MaintOrdOpComponentCurrency"`
	MatlCompIsMarkedForBackflush   bool        `json:"MatlCompIsMarkedForBackflush"`
	PurchasingGroup                string      `json:"PurchasingGroup"`
	DeliveryTimeInDays             string      `json:"DeliveryTimeInDays"`
	MaintOrdOpCompGdsRecipientName string      `json:"MaintOrdOpCompGdsRecipientName"`
	MaintOrdOpCompUnloadingPtTxt   string      `json:"MaintOrdOpCompUnloadingPtTxt"`
	GoodsReceiptDurationInWorkDays string      `json:"GoodsReceiptDurationInWorkDays"`
	PurchasingInfoRecord           string      `json:"PurchasingInfoRecord"`
	OperationLeadTimeOffset        string      `json:"OperationLeadTimeOffset"`
	OpsLeadTimeOffsetUnit          string      `json:"OpsLeadTimeOffsetUnit"`
	MaintOrdOpCompRequisitioner    string      `json:"MaintOrdOpCompRequisitioner"`
	MaintOrdOpCompProcmtTrckgNmbr  string      `json:"MaintOrdOpCompProcmtTrckgNmbr"`
	ResponsiblePurchaseOrg         string      `json:"ResponsiblePurchaseOrg"`
	MaintOrdOpCompSpecialStockType string      `json:"MaintOrdOpCompSpecialStockType"`
	VariableSizeDimension1         string      `json:"VariableSizeDimension1"`
	VariableSizeDimensionUnit      string      `json:"VariableSizeDimensionUnit"`
	VariableSizeCompFormulaKey     string      `json:"VariableSizeCompFormulaKey"`
	VariableSizeDimension2         string      `json:"VariableSizeDimension2"`
	NumberOfVariableSizeItem       int         `json:"NumberOfVariableSizeItem"`
	VariableSizeDimension3         string      `json:"VariableSizeDimension3"`
	VariableSizeItemQuantity       string      `json:"VariableSizeItemQuantity"`
	VariableSizeComponentUnit      string      `json:"VariableSizeComponentUnit"`
	RqmtDateIsEnteredManually      bool        `json:"RqmtDateIsEnteredManually"`
	SupplierProduct                string      `json:"SupplierProduct"`
	MaintOrdCompPurOutlineAgrmtItm string      `json:"MaintOrdCompPurOutlineAgrmtItm"`
	MaintOrderComponentInternalID  string      `json:"MaintOrderComponentInternalID"`
	PurchaseRequisition            string      `json:"PurchaseRequisition"`
	PurchaseRequisitionItem        string      `json:"PurchaseRequisitionItem"`
	OverallLimitAmount             string      `json:"OverallLimitAmount"`
	ExpectedOverallLimitAmount     string      `json:"ExpectedOverallLimitAmount"`
}
